name = "caac-logbook-worker"
main = "worker.js"
compatibility_date = "2024-03-01"

# ==========================================================
# 🚀 生产环境 (Production)
# ==========================================================
kv_namespaces = [
	{ binding = "FLIGHT_CACHE", id = "372feeb0a41f45b5a47935c0cf71c800" }
]

# ==========================================================
# 🧪 预发布环境 (Staging)
# ==========================================================
[env.staging]
name = "caac-logbook-worker-staging"
kv_namespaces = [
	{ binding = "FLIGHT_CACHE", id = "2fc9a28ddf304796bc20afcdb21ed3ce" }
]
