name = "flight-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
# ── API Keys ─────────────────────────────────────────────────────────────────

[[kv_namespaces]]
binding = "FLIGHT_CACHE"
id = "372feeb0a41f45b5a47935c0cf71c800"
